Kelin lab05 pick6
PdxCodeGuild/class_HB2 pull request #129
Opened 2022-08-02 01:09 UTC by rayk472

Version 1 pick6 lab. Still working on it.

2022-08-05 03:42 UTC, violette-git requested changes
Consider breaking the lab up into the steps given in the lab instructions. Let me know  if you have any questions.

2022-08-05 03:42 UTC, violette-git commented on code/kelin/labs/lab05_pick6.py
> +    for index in range(0,6):
Our ticket number is a list of 6 random numbers. take a look at the index you are specifying here. 0-6

2022-08-05 03:42 UTC, violette-git commented on code/kelin/labs/lab05_pick6.py
> +balance = [] # To show the amount of winnings
Balance should be given a value of 0 per lab instructions. Consider your balance like the pile of money you are paying tickets with. Except in this case that pile starts at 0.

2022-08-13 03:08 UTC, brucestull approved these changes
[Pick6](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/05%20Pick6.md)

**Completed**

Great use of variables. Good use of docstrings.

2022-08-13 03:08 UTC, merged