Justin django vue
PdxCodeGuild/class_HB2 pull request #276
Opened 2022-10-07 02:29 UTC by justin-young5

2022-10-07 02:29 UTC, justin-young5 commented
THIS IS THE POKEDEX

2022-10-11 00:41 UTC, violette-git commented on code/justin/Django/PokeVue/pokemon/templates/pokemon/poketemp.html
> +                        url: 'pokemon\templates\pokemon\papi.html',
I'm getting a server error because this url isnt a url. its a file path. I think what you want to do is make a request to the url that has your logic.

2022-10-11 00:42 UTC, violette-git requested changes
I couldn't even see what it looked like unfortunately. I  could not the get the data to load in. Check the comment I added in your review. I think this is causing the error. edit: wrong file was being looked in addition to cors error.

2022-10-13 21:42 UTC, violette-git approved these changes

2022-10-13 21:42 UTC, merged