Jonpan lab05 pick6
PdxCodeGuild/class_HB2 pull request #63
Opened 2022-07-09 02:58 UTC by notvert

2022-07-12 03:50 UTC, brucestull requested changes
[Lab 5: Pick6](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/05%20Pick6)

**Needs Work**

Comments:
* Labs need to be on their own branch. See me on how to break out labs 3 and 5 so they aren't on this same branch.

2022-07-13 01:24 UTC, notvert commented
Removed Lab03 from this branch

2022-07-14 01:26 UTC, brucestull requested changes
[Pick6](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/05%20Pick6.md)

**Needs Work**

2022-07-14 01:26 UTC, brucestull commented on code/jonpan/lab05.py
> +for x in range(loops):
* `winning_ticket` should be determined outside the loop. We want to compare 100000 player tickets to one `winning_ticket`.

2022-07-14 01:26 UTC, brucestull commented on code/jonpan/lab05.py
> +print(payoff)
* Lab needs to provide `ROI`.

2022-07-15 01:50 UTC, brucestull requested changes
**Needs Work**

Comments:
* Need to resolve merge conflict.
* I think that students have been deleting old lab 'files' from their branch since I haven't been doing an adequate job of explaining the concept of what git is for. Old labs 'files' should show up on new branches, BUT they only become noticable when we try to edit them. It's expected for old labs which have been merged into main, and then become part of new lab branches, to show on new branches. We don't want to delete them. They are part of branch `main` now.
* It can be quite a challenge to understand these concepts. Let's discuss and also try to find some git tutorials to it makes sense.

Please see me so we can discuss. This is an important concept.

2022-07-15 02:10 UTC, notvert commented
I'm going to create a new branch to resolve this error like I did for previous labs.

2022-07-15 02:10 UTC, closed without merging