Muki lab02 converter
PdxCodeGuild/class_HB2 pull request #64
Opened 2022-07-09 04:31 UTC by Muki-has-ideas

Lab 02 done up through version 2.

2022-07-12 04:04 UTC, brucestull requested changes
[Lab 02: Unit Converter](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/02%20Unit%20Converter)

**Needs Work**

Comments:
* User input of `72` `in` results in no output. Expected output is some value in `meters`.
    * Sample input and output:
    ```
    PS C:\Users\Bruce\Programming\class_HB2\code\muki> git status
    On branch muki-lab02-converter
    Your branch is up to date with 'origin/muki-lab02-converter'.

    nothing to commit, working tree clean
    PS C:\Users\Bruce\Programming\class_HB2\code\muki>
    PS C:\Users\Bruce\Programming\class_HB2\code\muki> python .\lab02.py

    Enter the length that you would like to convert to meters:      72
    Enter the units: (km, mi, ft, in, mm, yd:       in
    PS C:\Users\Bruce\Programming\class_HB2\code\muki>
    ```
* Math operators should have single-space before and after. See [PEP8 style guide](https://peps.python.org/pep-0008/#other-recommendations)
* Great use of float so output can be non-integer.

2022-07-15 02:13 UTC, brucestull approved these changes
[Lab 02: Unit Converter](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/02%20Unit%20Converter)

**Completed**

Comments:
* Lab performs requirements
* In future labs, be aware of PEP8 Style guide. Ensure proper whitespace to enhance code readability.

2022-07-15 02:13 UTC, brucestull commented on code/muki/lab02.py
> +if dist_unit.lower() == 'km':
* Math operators should be surrounded by single-spaces for readability.
    * `variable_one*variable_two` should be `variable_one * variable_two`

2022-07-15 02:13 UTC, merged

2022-07-15 02:20 UTC, Muki-has-ideas commented
thanks Bruce