Daniel lab04 blackjack advice
PdxCodeGuild/class_HB2 pull request #68
Opened 2022-07-12 00:57 UTC by DanielD6464

Lab 4 Blackjack Finished

2022-07-14 01:51 UTC, brucestull requested changes
[Blackjack Advice](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/04%20Black%20Jack%20Advice.md)

**Needs Work**

Comments:
* Need to change variables to `snake_case`.

2022-07-14 01:51 UTC, brucestull commented on code/daniel/04_BlackJackAdvice/daniel-Lab4-Blackjack Advice.py
> +Facecards = {
* For Python, variables like `Facecards` should be in snake_case (`face_cards`). See [PEP8 Naming Conventions](https://peps.python.org/pep-0008/#naming-conventions)

2022-07-14 01:51 UTC, brucestull commented on code/daniel/04_BlackJackAdvice/daniel-Lab4-Blackjack Advice.py
> +Question1 = input("What's your first card?: ")
* Better naming would be `question_1` etc. (`snake_case`).

2022-07-14 01:51 UTC, brucestull commented on code/daniel/04_BlackJackAdvice/daniel-Lab4-Blackjack Advice.py
> +cardTotal = 0
* `cardTotal` is camelCase (usually in Javascript). Use `snake_case` in Python. So `cardTotal` should be `card_total`.

2022-07-19 02:14 UTC, nathanBonilla submitted a review, later dismissed
Hey Daniel, great job with your lab, I loved your utilization of dictionaries!
What I'd like to see before I approve your PR is either input validation, or final error.
What I mean is that, when I enter an invalid character, the program will still continue and output a result as if the invalid character didn't exist:
 - I'll enter 10, !, 10
 - The output will be a 20 even though there's a invalid card in my hand
There's two ways to tackle this.  Either ensure that I don't enter an invalid card, or let me know that my answer doesn't matter because there's an invalid card in my hand.

Once you make that fix, you're golden!

2022-07-21 23:59 UTC, DanielD6464 commented
Bruce said to grade lab 4 and ignore lab 7.

2022-07-22 01:44 UTC, brucestull commented
Great job, Daniel!

[Blackjack Advice](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/04%20Black%20Jack%20Advice.md)

**Completed**

2022-07-22 01:45 UTC, brucestull approved these changes

2022-07-22 01:46 UTC, merged