resubmitting lab05 on a new branch
PdxCodeGuild/class_HB2 pull request #84
Opened 2022-07-15 02:41 UTC by notvert

Moved winning ticket outside of loop as requested by Bruce

2022-07-19 23:44 UTC, brucestull commented
Original Pull Request (which was closed so student could create new branch without merge conflicts): https://github.com/PdxCodeGuild/class_HB2/pull/63

2022-07-19 23:49 UTC, brucestull requested changes
[Pick6](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/05%20Pick6.md)

**Needs Work**

Comments:
* Lab needs Version 2, display the ROI: "The ROI (return on investment) is defined as (earnings - expenses)/expenses. Calculate your ROI, print it out along with your earnings and expenses."

2022-07-21 02:25 UTC, brucestull submitted a review, later dismissed
[Pick6](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/05%20Pick6.md)

**Needs Work**

Comments:
* Lab should use the provided equation for ROI:
```
roi = (earnings - expenses)/expenses
```

2022-07-21 02:25 UTC, brucestull commented on code/jonpan/lab05.py
> +ROI = (payoff - ticket_cost) / payoff
* ROI should be calculated using formula in lab document. Make sure to use the variables so the ROI calcualtion uses the specific form below:
```
roi = (earnings - expenses)/expenses
```

2022-07-22 02:08 UTC, notvert commented on code/jonpan/lab05.py
> +ROI = (payoff - ticket_cost) / payoff
Changes submitted

2022-07-22 02:19 UTC, nathanBonilla approved these changes
Great job Jon!

2022-07-22 02:21 UTC, merged