commiting lab3 and ready to push
PdxCodeGuild/class_HB2 pull request #87
Opened 2022-07-16 02:33 UTC by Muki-has-ideas

pull request for lab 3. hooray

2022-07-16 04:06 UTC, Muki-has-ideas commented
add version 2 will

2022-07-19 01:44 UTC, Muki-has-ideas commented
done-zo

2022-07-20 01:46 UTC, brucestull requested changes
[Lab 3: Number to Phrase](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/03%20Number%20To%20Phrases.md)

**Needs Work**

Comments:
* User input of `510` results in improper output: Expected would be like `five hundred ten` but result was `five hundred-zero`.
* Sample output:
```
PS C:\Users\Bruce\Programming\class_HB2\code\muki> python .\lab03.py
please enter a number between 0 and 999:
510
You entered:510  Thanks for your entry.
0
1
5
10
510 is: five hundred-zero
PS C:\Users\Bruce\Programming\class_HB2\code\muki>
```

2022-07-20 01:46 UTC, brucestull commented on code/muki/lab03.py
> +hundreds_place = int(numbah)//100
* See [PEP8](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements) for readability and style guidance.
* Math operators should be surrounded by single-spaces.
* Typically, a single space should follow colons in dictionaries and some commas. Check out the PEP8 documentation linked above.

2022-07-20 01:46 UTC, brucestull commented on code/muki/lab03.py
> +single_digits = {
* For PEP8 Style Guide
* Single spaces after colons in dictionaries can help with readability.

2022-07-23 02:27 UTC, brucestull requested changes
[Lab 3: Number to Phrase](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/03%20Number%20To%20Phrases.md)

**Needs Work**

Comments:
* Input of `108` results in improper output. See below log:
```
PS C:\Users\Bruce\Programming\class_HB2\code\muki> python .\lab03.py
please enter a number between 0 and 999:
108
8
You entered:108  Thanks for your entry.
8
0
1
8
PS C:\Users\Bruce\Programming\class_HB2\code\muki>
```

2022-07-25 17:45 UTC, brucestull requested changes
**Needs Work**

Comments:
* Entry of `999` results in two answers. Only one result should show. Please remove unnecessary print outputs. Only have one print output of final answer.
    ```
    PS C:\Users\Bruce\Programming\class_HB2\code\muki> python .\lab03.py
    please enter a number between 0 and 999:
    999
    99
    You entered:999  Thanks for your entry.
    9
    9
    9
    99
    999 is: ninety-nine
    999 is: nine hundred ninety-nine
    PS C:\Users\Bruce\Programming\class_HB2\code\muki>
    ```
* Entry of `101` results does not produce expected results. Expected results would be something like `one hundred one`.
    ```
    PS C:\Users\Bruce\Programming\class_HB2\code\muki> python .\lab03.py
    please enter a number between 0 and 999:
    101
    1
    You entered:101  Thanks for your entry.
    1
    0
    1
    1
    PS C:\Users\Bruce\Programming\class_HB2\code\muki>
    ```

2022-07-26 01:51 UTC, brucestull requested changes
**Needs Work**

Comments:
* Input of `101` results in `one hundred`. Expected output would be something like `one hundred one`.
```
PS C:\Users\Bruce\Programming\class_HB2\code\muki> python .\lab03.py
please enter a number between 0 and 999:
> 101
You entered:101  Thanks for your entry.
101 is: one hundred
PS C:\Users\Bruce\Programming\class_HB2\code\muki>
```

2022-07-28 01:11 UTC, brucestull approved these changes
**Completed**

2022-07-28 01:11 UTC, merged