Muki lab04 blackjackv2
PdxCodeGuild/class_HB2 pull request #94
Opened 2022-07-19 02:25 UTC by Muki-has-ideas

need some review and whatnot.  Please take a look and let me know folks ^_^

2022-07-19 03:57 UTC, brucestull requested changes
[Blackjack Advice](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/04%20Black%20Jack%20Advice.md)

**Needs Work**

Comments:
* User input of three cards of value '4' doesn't produce advice after third card. See output below:
```
PS C:\Users\Bruce\Programming\class_HB2\code\muki> python .\lab04b.py
What is your first card?        4
What is your second card?       4
8 Hit!
What is the next card?  4
PS C:\Users\Bruce\Programming\class_HB2\code\muki>
```

2022-07-19 03:57 UTC, brucestull commented on code/muki/lab04b.py
> +total = int(card_values[card1]) + int(card_values[card2])
If you use `string:int` key:value pairs like `'J': 10` rather than `'J': '10'`, you won't need to cast the dictionary string values to int.

2022-07-19 03:57 UTC, brucestull commented on code/muki/lab04b.py
> +card_values = {
* It would be useful to use str:int key-value pairs in the dictionary rather than str:str key-value pairs. Since you are doing math on the values, it might make sense to use ints instead of strings.

2022-07-19 04:16 UTC, Muki-has-ideas commented on code/muki/lab04b.py
> +total = int(card_values[card1]) + int(card_values[card2])
Thanks Bruce, I'll resolve that. Also I will need to add some to keep it going until 17 or  bust.

2022-07-23 02:19 UTC, brucestull approved these changes
[Blackjack Advice](https://github.com/PdxCodeGuild/class_HB2/blob/main/1%20Python/labs/04%20Black%20Jack%20Advice.md)

**Completed**

Comments:
* Great work

2022-07-23 02:19 UTC, merged